#!/bin/bash

echo "# File @generated by ./generate-authors.sh. DO NOT EDIT."
echo "# This file lists all contributors to the repository."
echo "# See ./generate-authors.sh to make modifications."
echo ""

# Auteurs principaux
echo "Jules Moleins <10446@holbertonstudents.com>"
echo "Pierre-Yves Fauconnet <10450@holbertonstudents.com>"

# Autres contributeurs Git (sans doublons)
git log --format='%aN <%aE>' | sort -u | grep -v -e '10446@holbertonstudents.com' -e '10450@holbertonstudents.com'
